import { THEATER_STATUS } from "../../enums";

export interface ITheater {
  id: number;
  admin_id: number;
  name: string;
  code: string; // short name of the theater, e.g. "BSC"
  location: string;
  status: THEATER_STATUS;
  created_at: Date;
  updated_at: Date;
}

// this type for theater creation, id, status, created_at, updated_at will be generated by the system.
export type ICreateTheater = Omit<
  ITheater,
  "id" | "status" | "created_at" | "updated_at"
>;

// Update = every create field optional also is_active toggle.
export type IUpdateTheater = Partial<ICreateTheater> & {
  status?: THEATER_STATUS;
};
